In [1]:
import pandas as pd
df = pd.read_csv(
    "../dados/siga-empreendimentos-geracao.csv",
    sep=";",
    encoding="utf-8",
    low_memory=False
)

In [2]:
df.shape

(25045, 23)

In [3]:
df.columns.tolist()

['DatGeracaoConjuntoDados',
 'NomEmpreendimento',
 'IdeNucleoCEG',
 'CodCEG',
 'SigUFPrincipal',
 'SigTipoGeracao',
 'DscFaseUsina',
 'DscOrigemCombustivel',
 'DscFonteCombustivel',
 'DscTipoOutorga',
 'NomFonteCombustivel',
 'DatEntradaOperacao',
 'MdaPotenciaOutorgadaKw',
 'MdaPotenciaFiscalizadaKw',
 'MdaGarantiaFisicaKw',
 'IdcGeracaoQualificada',
 'NumCoordNEmpreendimento',
 'NumCoordEEmpreendimento',
 'DatInicioVigencia',
 'DatFimVigencia',
 'DscPropriRegimePariticipacao',
 'DscSubBacia',
 'DscMuninicpios']

In [4]:
df.head()

,DatGeracaoConjuntoDados,NomEmpreendimento,IdeNucleoCEG,CodCEG,SigUFPrincipal,SigTipoGeracao,DscFaseUsina,DscOrigemCombustivel,DscFonteCombustivel,DscTipoOutorga,...,MdaPotenciaFiscalizadaKw,MdaGarantiaFisicaKw,IdcGeracaoQualificada,NumCoordNEmpreendimento,NumCoordEEmpreendimento,DatInicioVigencia,DatFimVigencia,DscPropriRegimePariticipacao,DscSubBacia,DscMuninicpios
0,2026-10-01,E,8,PCH.PH.MG.000008-6.1,MG,PCH,Operação,Hídrica,Potencial hidráulico,Autorização,...,1400,",00",Não,"-20,12479858","-43,87020250",2000-07-07,2030-07-07,100% para ANGLOGOLD ASHANTI CORREGO DO SITIO M...,41 - Das Velhas - Sao Francisco,Nova Lima - MG
1,2026-10-01,F,9,PCH.PH.MG.000009-4.1,MG,PCH,Operação,Hídrica,Potencial hidráulico,Autorização,...,3972,",00",Não,"-20,13187300","-43,87693500",2000-07-07,2030-07-07,100% para ANGLOGOLD ASHANTI CORREGO DO SITIO M...,41 - Das Velhas - Sao Francisco,Nova Lima - MG
2,2026-10-01,G,10,PCH.PH.MG.000010-8.1,MG,PCH,Operação,Hídrica,Potencial hidráulico,Autorização,...,1440,",00",Não,"-20,13754468","-43,89192620",2000-08-31,2030-08-31,100% para ANGLOGOLD ASHANTI CORREGO DO SITIO M...,41 - Das Velhas - Sao Francisco,Nova Lima - MG
3,2026-10-01,14 de Julho,12,UHE.PH.RS.000012-4.1,RS,UHE,Operação,Hídrica,Potencial hidráulico,Concessão,...,100000,"45200,00",Não,"-29,06475278","-51,67494167",2001-03-15,2039-11-13,100% para CERAN - COMPANHIA ENERGETICA RIO DAS...,86 - Taquari,"Bento Gonçalves - RS, Cotiporã - RS"
4,2026-10-01,Abaúna,15,CGH.PH.RS.000015-9.1,RS,CGH,Operação,Hídrica,Potencial hidráulico,Registro,...,720,",00",Não,"-27,82377500","-52,06999722",NaN,NaN,50% para CRERAL- COOPERATIVA DE GERACAO DE ENE...,"72 - Uruguai, Inhanduva, Peixe e outros",Floriano Peixoto - RS

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 25045 entries, 0 to 25044
Data columns (total 23 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   DatGeracaoConjuntoDados       25045 non-null  str
 1   NomEmpreendimento             25045 non-null  str
 2   IdeNucleoCEG                  25045 non-null  int64
 3   CodCEG                        25045 non-null  str
 4   SigUFPrincipal                25045 non-null  str
 5   SigTipoGeracao                25045 non-null  str
 6   DscFaseUsina                  25045 non-null  str
 7   DscOrigemCombustivel          25045 non-null  str
 8   DscFonteCombustivel           25045 non-null  str
 9   DscTipoOutorga                25045 non-null  str
 10  NomFonteCombustivel           25045 non-null  str
 11  DatEntradaOperacao            25045 non-null  str
 12  MdaPotenciaOutorgadaKw        25045 non-null  str
 13  MdaPotenciaFiscalizadaKw      25045 non-null  int64
 14  MdaGarantiaFisicaKw           25045 non-null  str
 15  IdcGeracaoQualificada         9088 non-null   str
 16  NumCoordNEmpreendimento       25045 non-null  str
 17  NumCoordEEmpreendimento       25045 non-null  str
 18  DatInicioVigencia             5362 non-null   str
 19  DatFimVigencia                5352 non-null   str
 20  DscPropriRegimePariticipacao  25045 non-null  str
 21  DscSubBacia                   1456 non-null   str
 22  DscMuninicpios                25045 non-null  str
dtypes: int64(2), str(21)
memory usage: 4.4 MB

In [6]:
df.isna().sum().sort_values(ascending=False)

DscSubBacia                     23589
DatFimVigencia                  19693
DatInicioVigencia               19683
IdcGeracaoQualificada           15957
DatGeracaoConjuntoDados             0
NomEmpreendimento                   0
IdeNucleoCEG                        0
DscFaseUsina                        0
SigTipoGeracao                      0
SigUFPrincipal                      0
CodCEG                              0
DscOrigemCombustivel                0
DscFonteCombustivel                 0
DscTipoOutorga                      0
NomFonteCombustivel                 0
MdaGarantiaFisicaKw                 0
MdaPotenciaFiscalizadaKw            0
MdaPotenciaOutorgadaKw              0
DatEntradaOperacao                  0
NumCoordEEmpreendimento             0
NumCoordNEmpreendimento             0
DscPropriRegimePariticipacao        0
DscMuninicpios                      0
dtype: int64

In [7]:
df["SigUFPrincipal"].value_counts(dropna=False)

SigUFPrincipal
PA    13204
MS     3020
MG     1299
SP     1194
BA     1163
RN      595
CE      585
RS      536
SC      530
PI      513
PR      328
MT      306
GO      280
PE      272
RJ      226
PB      208
AM      181
ES      114
RR      102
TO       85
RO       64
MA       63
AL       57
SE       54
AC       30
DF       24
AP       12
Name: count, dtype: int64

In [8]:
df["DscFaseUsina"].value_counts(dropna=False)

DscFaseUsina
Operação                   22801
Construção não iniciada     2099
Construção                   145
Name: count, dtype: int64

In [9]:
df["DscOrigemCombustivel"].value_counts(dropna=False)

DscOrigemCombustivel
Solar       18962
Fóssil       2360
Eólica       1549
Hídrica      1476
Biomassa      695
Nuclear         3
Name: count, dtype: int64

In [10]:
print(df["CodCEG"].nunique(), len(df))

25042 25045

In [11]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 25045 entries, 0 to 25044
Data columns (total 23 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   DatGeracaoConjuntoDados       25045 non-null  str
 1   NomEmpreendimento             25045 non-null  str
 2   IdeNucleoCEG                  25045 non-null  int64
 3   CodCEG                        25045 non-null  str
 4   SigUFPrincipal                25045 non-null  str
 5   SigTipoGeracao                25045 non-null  str
 6   DscFaseUsina                  25045 non-null  str
 7   DscOrigemCombustivel          25045 non-null  str
 8   DscFonteCombustivel           25045 non-null  str
 9   DscTipoOutorga                25045 non-null  str
 10  NomFonteCombustivel           25045 non-null  str
 11  DatEntradaOperacao            25045 non-null  str
 12  MdaPotenciaOutorgadaKw        25045 non-null  str
 13  MdaPotenciaFiscalizadaKw      25045 non-null  int64
 14  MdaGarantiaFisicaKw           25045 non-null  str
 15  IdcGeracaoQualificada         9088 non-null   str
 16  NumCoordNEmpreendimento       25045 non-null  str
 17  NumCoordEEmpreendimento       25045 non-null  str
 18  DatInicioVigencia             5362 non-null   str
 19  DatFimVigencia                5352 non-null   str
 20  DscPropriRegimePariticipacao  25045 non-null  str
 21  DscSubBacia                   1456 non-null   str
 22  DscMuninicpios                25045 non-null  str
dtypes: int64(2), str(21)
memory usage: 4.4 MB

In [12]:
df.isna().sum().sort_values(ascending=False)

DscSubBacia                     23589
DatFimVigencia                  19693
DatInicioVigencia               19683
IdcGeracaoQualificada           15957
DatGeracaoConjuntoDados             0
NomEmpreendimento                   0
IdeNucleoCEG                        0
DscFaseUsina                        0
SigTipoGeracao                      0
SigUFPrincipal                      0
CodCEG                              0
DscOrigemCombustivel                0
DscFonteCombustivel                 0
DscTipoOutorga                      0
NomFonteCombustivel                 0
MdaGarantiaFisicaKw                 0
MdaPotenciaFiscalizadaKw            0
MdaPotenciaOutorgadaKw              0
DatEntradaOperacao                  0
NumCoordEEmpreendimento             0
NumCoordNEmpreendimento             0
DscPropriRegimePariticipacao        0
DscMuninicpios                      0
dtype: int64

In [13]:
df["SigTipoGeracao"].value_counts(dropna=False)

SigTipoGeracao
UFV    18962
UTE     3055
EOL     1549
CGH      718
PCH      537
UHE      221
UTN        3
Name: count, dtype: int64

In [14]:
df["MdaPotenciaOutorgadaKw"].head(10)

0      1400,00
1      3972,00
2      1440,00
3    100000,00
4       720,00
5      1460,00
6    102890,00
7     14040,00
8     14040,00
9       224,80
Name: MdaPotenciaOutorgadaKw, dtype: str

In [15]:
dup = df[df.duplicated("CodCEG", keep=False)].sort_values("CodCEG")

In [16]:
dup[["CodCEG", "NomEmpreendimento", "SigUFPrincipal", "DscFaseUsina", "MdaPotenciaOutorgadaKw"]]

,CodCEG,NomEmpreendimento,SigUFPrincipal,DscFaseUsina,MdaPotenciaOutorgadaKw
1094,PCH.PH.SC.028744-0.1,Rio Timbó,SC,Operação,"5500,00"
1095,PCH.PH.SC.028744-0.1,Rio Timbó,SC,Operação,"5500,00"
7,PCH.PH.TO.000031-0.1,Agro Trafo,TO,Operação,"14040,00"
8,PCH.PH.TO.000031-0.1,Agro Trafo,TO,Operação,"14040,00"
285,UHE.PH.MG.001489-3.1,Monte Alto,MG,Operação,"7360,00"
286,UHE.PH.MG.001489-3.1,Monte Alto,MG,Operação,"7360,00"

In [17]:
df.duplicated().sum()

np.int64(0)

In [18]:
dup.T

,1094,1095,7,8,285,286
DatGeracaoConjuntoDados,2026-10-01,2026-10-01,2026-10-01,2026-10-01,2026-10-01,2026-10-01
NomEmpreendimento,Rio Timbó,Rio Timbó,Agro Trafo,Agro Trafo,Monte Alto,Monte Alto
IdeNucleoCEG,28744,28744,31,31,1489,1489
CodCEG,PCH.PH.SC.028744-0.1,PCH.PH.SC.028744-0.1,PCH.PH.TO.000031-0.1,PCH.PH.TO.000031-0.1,UHE.PH.MG.001489-3.1,UHE.PH.MG.001489-3.1
SigUFPrincipal,SC,SC,TO,TO,MG,MG
SigTipoGeracao,PCH,PCH,PCH,PCH,UHE,UHE
DscFaseUsina,Operação,Operação,Operação,Operação,Operação,Operação
DscOrigemCombustivel,Hídrica,Hídrica,Hídrica,Hídrica,Hídrica,Hídrica
DscFonteCombustivel,Potencial hidráulico,Potencial hidráulico,Potencial hidráulico,Potencial hidráulico,Potencial hidráulico,Potencial hidráulico
DscTipoOutorga,Autorização,Concessão,Autorização,Concessão,Autorização,Concessão
NomFonteCombustivel,Potencial hidráulico,Potencial hidráulico,Potencial hidráulico,Potencial hidráulico,Potencial hidráulico,Potencial hidráulico
DatEntradaOperacao,1959-08-15,1959-08-15,1992-01-01,1992-01-01,1952-02-27,1952-02-27
MdaPotenciaOutorgadaKw,"5500,00","5500,00","14040,00","14040,00","7360,00","7360,00"
MdaPotenciaFiscalizadaKw,5500,5500,14040,14040,7360,7360
MdaGarantiaFisicaKw,",00",",00","6800,00","6800,00",",00",",00"
IdcGeracaoQualificada,Não,Não,Não,Não,Não,Não
NumCoordNEmpreendimento,"-26,49361111","-26,49361111","-11,67563889","-11,67563889","-20,78236443","-20,78236443"
NumCoordEEmpreendimento,"-50,78638889","-50,78638889","-46,66815833","-46,66815833","-46,72243018","-46,72243018"
DatInicioVigencia,2014-09-13,2014-09-13,2017-07-13,2017-07-13,2024-12-29,2024-12-29
DatFimVigencia,2044-09-13,2044-09-13,2047-07-13,2047-07-13,2054-12-29,2054-12-29
DscPropriRegimePariticipacao,100% para CIA BOM SUCESSO DE ELETRICIDADE - 83...,100% para CIA BOM SUCESSO DE ELETRICIDADE - 83...,100% para SOCIBE ENERGIA S.A. - 02.131.646/000...,100% para SOCIBE ENERGIA S.A. - 02.131.646/000...,100% para VOTORANTIM CIMENTOS S.A. - 01.637.89...,100% para VOTORANTIM CIMENTOS S.A. - 01.637.89...
DscSubBacia,"65 - Parana, Iguacu","65 - Parana, Iguacu","21 - Tocantins, entre os rios Preto e Parana","21 - Tocantins, entre os rios Preto e Parana",61 - Grande,61 - Grande
DscMuninicpios,"Irineópolis - SC, Porto União - SC","Irineópolis - SC, Porto União - SC",Dianópolis - TO,Dianópolis - TO,Passos - MG,Passos - MG

## Descobertas da exploração

- Base com 25.045 linhas e 23 colunas (geração centralizada, ANEEL/SIGA)
- 27 UFs, sem nulos nem grafias diferentes
- Fase: 91% em operação, o resto em construção ou não iniciada
- Fonte: usar DscOrigemCombustivel (6 categorias limpas)
- Potência veio como texto com vírgula decimal, em kW -> converter para número e MW
- 3 códigos (CodCEG) repetidos, todos hidrelétricas -> verificar se são cópias exatas
- 4 colunas quase vazias (sub-bacia, vigência, geração qualificada) -> descartar
- O Pará concentra 53% das linhas e solar 76% -> investigar tamanho das usinas

- 3 códigos (CodCEG) repetidos: mesma usina com dois tipos de outorga
  (Autorização e Concessão). Decisão: manter uma linha por CodCEG.
- Datas em formato aaaa-mm-dd; base gerada em 2026-10-01

In [19]:
df_limpo = df.copy()

In [20]:
df_limpo = df_limpo.drop_duplicates(subset="CodCEG", keep="first")

In [21]:
print(len(df), len(df_limpo), df_limpo["CodCEG"].is_unique)

25045 25042 True

In [22]:
colunas = [
    "CodCEG",
    "NomEmpreendimento",
    "SigUFPrincipal",
    "SigTipoGeracao",
    "DscFaseUsina",
    "DscOrigemCombustivel",
    "DatEntradaOperacao",
    "MdaPotenciaOutorgadaKw",
    "MdaPotenciaFiscalizadaKw",

]

In [23]:
df_limpo = df_limpo[colunas].copy()

In [24]:
df_limpo.shape

(25042, 9)

In [25]:
df_limpo.head()

,CodCEG,NomEmpreendimento,SigUFPrincipal,SigTipoGeracao,DscFaseUsina,DscOrigemCombustivel,DatEntradaOperacao,MdaPotenciaOutorgadaKw,MdaPotenciaFiscalizadaKw
0,PCH.PH.MG.000008-6.1,E,MG,PCH,Operação,Hídrica,1953-11-20,"1400,00",1400
1,PCH.PH.MG.000009-4.1,F,MG,PCH,Operação,Hídrica,1953-11-20,"3972,00",3972
2,PCH.PH.MG.000010-8.1,G,MG,PCH,Operação,Hídrica,1937-01-01,"1440,00",1440
3,UHE.PH.RS.000012-4.1,14 de Julho,RS,UHE,Operação,Hídrica,2008-12-25,"100000,00",100000
4,CGH.PH.RS.000015-9.1,Abaúna,RS,CGH,Operação,Hídrica,2000-10-15,"720,00",720

In [26]:
df_limpo["potencia_outorgada_mw"] = pd.to_numeric(df_limpo["MdaPotenciaOutorgadaKw"].str.replace(",", "."), errors="coerce") / 1000

In [27]:
df_limpo["potencia_outorgada_mw"].isna().sum()

np.int64(0)

In [28]:
df_limpo["potencia_fiscalizada_mw"] = df_limpo["MdaPotenciaFiscalizadaKw"] / 1000

In [29]:
df_limpo[["potencia_outorgada_mw", "potencia_fiscalizada_mw"]].describe()

       potencia_outorgada_mw  potencia_fiscalizada_mw
count           25042.000000             25042.000000
mean               12.685913                 8.813336
std               124.220623               122.921232
min                 0.000010                 0.000000
25%                 0.001000                 0.001000
50%                 0.001000                 0.001000
75%                 1.308400                 0.136000
max             11233.100000             11233.100000

In [30]:
operacao = df_limpo[df_limpo["DscFaseUsina"] == "Operação"]

In [31]:
resumo = operacao.groupby("DscOrigemCombustivel").agg(
    usinas=("CodCEG", "count"),
    potencia_mw=("potencia_fiscalizada_mw", "sum"),
)
resumo["pct_usinas"] = (100 * resumo["usinas"] / resumo["usinas"].sum()).round(1)
resumo["pct_potencia"] = (100 * resumo["potencia_mw"] / resumo["potencia_mw"].sum()).round(1)
resumo.sort_values("potencia_mw", ascending=False)

                      usinas  potencia_mw  pct_usinas  pct_potencia
DscOrigemCombustivel
Hídrica                 1359   110226.812         6.0          50.0
Eólica                  1138    34936.651         5.0          15.8
Fóssil                  2340    31839.248        10.3          14.4
Solar                  17302    23615.261        75.9          10.7
Biomassa                 657    18050.914         2.9           8.2
Nuclear                    2     1990.000         0.0           0.9

In [32]:
pa = operacao[operacao["SigUFPrincipal"] == "PA"]
pa["SigTipoGeracao"].value_counts()
pa["potencia_fiscalizada_mw"].describe()

count    13201.000000
mean         1.777644
std        124.073429
min          0.000000
25%          0.001000
50%          0.001000
75%          0.001000
max      11233.100000
Name: potencia_fiscalizada_mw, dtype: float64

In [33]:
df_limpo["porte"] = pd.cut(
    df_limpo["potencia_outorgada_mw"],
    bins=[-1, 0.075, 5, 100, float("inf")],
    labels=["Micro", "Pequena", "Média", "Grande"],
)

In [34]:
operacao = df_limpo[df_limpo["DscFaseUsina"] == "Operação"]
operacao.groupby("porte", observed=True)["potencia_fiscalizada_mw"].agg(["count", "sum"])

         count         sum
porte
Micro    16297      28.946
Pequena   3598    4546.637
Média     2680   83152.361
Grande     223  132930.942

In [35]:
df_limpo["data_operacao"] = pd.to_datetime(df_limpo["DatEntradaOperacao"], errors="coerce")
df_limpo["ano_operacao"] = df_limpo["data_operacao"].dt.year

In [36]:
df_limpo.groupby("DscFaseUsina")["ano_operacao"].agg(["count", "min", "max"])

                         count   min   max
DscFaseUsina
Construção                 145  1900  2026
Construção não iniciada   2099  1900  1900
Operação                 22798  1900  2026

In [37]:
df_limpo.loc[df_limpo["data_operacao"].dt.year == 1900, "data_operacao"] = pd.NaT
df_limpo["ano_operacao"] = df_limpo["data_operacao"].dt.year

In [38]:
df_limpo.groupby("DscFaseUsina")["ano_operacao"].agg(["count", "min", "max"])

                         count     min     max
DscFaseUsina
Construção                   1  2026.0  2026.0
Construção não iniciada      0     NaN     NaN
Operação                 22642  1901.0  2026.0

In [39]:
final = df_limpo.rename(columns={
    "CodCEG": "cod_ceg",
    "NomEmpreendimento": "nome",
    "SigUFPrincipal": "uf",
    "SigTipoGeracao": "tipo_geracao",
    "DscFaseUsina": "fase",
    "DscOrigemCombustivel": "fonte",
})[["cod_ceg", "nome", "uf", "tipo_geracao", "fase", "fonte", "porte",
    "data_operacao", "ano_operacao", "potencia_outorgada_mw", "potencia_fiscalizada_mw"]]

final["ano_operacao"] = final["ano_operacao"].astype("Int64")
final.shape

(25042, 11)

In [40]:
final.to_csv("../dados/usinas_limpo.csv", index=False)

In [ ]:
final.to_csv("../dados/usinas_limpo_ansi.csv", index=False, encoding="cp1252")